tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
brew "asdf"
brew "bash-completion"
brew "brew-cask-completion"
brew "cask"
brew "chezmoi"
brew "libpng"
brew "colima"
brew "elixir"
brew "exercism"
brew "ghostscript"
brew "gifsicle"
brew "git"
brew "openssl@1.1"
brew "httrack"
brew "mas"
brew "neovim"
brew "nghttp2"
brew "python@3.9", link: false
brew "ripgrep"
brew "ruby", link: true
brew "tmux"
brew "tree"
brew "x264"
brew "xvid"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "adobe-acrobat-reader"
cask "alacritty"
cask "anki"
cask "ankiapp"
cask "appcleaner"
cask "authy"
cask "battle-net"
cask "bitwarden"
cask "cheatsheet"
cask "docker"
cask "dropbox"
cask "evernote"
cask "font-jetbrains-mono-nerd-font"
cask "gimp"
cask "git-credential-manager"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "logi-options+"
cask "middleclick"
cask "nordvpn"
cask "obsidian"
cask "postman"
cask "rectangle"
cask "spotify"
cask "steam"
cask "teamviewer"
cask "todoist"
cask "visual-studio-code"
cask "webtorrent"
cask "zoom"
mas "DigiDoc4 Client", id: 1370791134
mas "feedly", id: 865500966
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TeRa", id: 1243347809
mas "Xcode", id: 497799835
