#!/bin/bash

## Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

## install packages in Brewbundle file
## Brewfile generated by 'brew bundle --no-vscode -f'
brew bundle

# Install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source ~/.tmux.conf
~/.tmux/plugins/tpm/bin/install_plugins

# Terraform Autocomplete
terraform -install-autocomplete
